name: 'Changelog Parser'
description: 'Reads and parses CHANGELOG.md files from local paths or remote URLs, following the Keep a Changelog standard'
inputs:
  path:
    description: 'Path to changelog file or URL (defaults to ./CHANGELOG.md). Supports local paths and remote URLs from any source'
    required: false
    default: './CHANGELOG.md'
  token:
    description: 'Optional authentication token (defaults to github.token). Only used when path is a remote URL that requires authentication'
    required: false
  version:
    description: 'The exact version of the log entry to retrieve or "Unreleased" for the unreleased entry. Defaults to the last version number'
    required: false
  validation-level:
    description: 'Specifies at which level the validation system is set. Can be none, warn, or error'
    required: false
    default: 'none'
  validation-depth:
    description: 'Specifies how many entries to validate in the CHANGELOG.md file'
    required: false
    default: '10'
  config-file:
    description: 'Path to a configuration file. If not specified, will look for .changelog-reader.json, .changelog-reader.yml, .changelog-reader.yaml, .changelogrc, or .changelogrc.json in the repository root'
    required: false
  repo-url:
    description: 'Repository URL (e.g., https://github.com/owner/repo). When path is blank, CHANGELOG.md will be fetched from the root of this repository'
    required: false
  ref:
    description: 'Branch or ref to use when constructing CHANGELOG.md URL from repoUrl (defaults to main)'
    required: false
    default: 'main'
  repo-type:
    description: 'Repository platform type (auto, github, gitea, gitlab, bitbucket). Defaults to auto which attempts to detect from domain. Use explicit type for custom domains'
    required: false
    default: 'auto'
  verbose:
    description: 'Enable verbose debug logging. Also enabled when ACTIONS_STEP_DEBUG=true.'
    required: false
    default: 'false'
  skip-certificate-check:
    description: 'Skip TLS certificate verification (useful for self-hosted instances with self-signed certificates). WARNING: This is a security risk and should only be used with trusted self-hosted instances'
    required: false
    default: 'false'
  output-file:
    description: 'Optional file path to write the changelog changes content to (e.g., .release-notes.md). Use this to avoid YAML interpolation issues when passing long or special-character content to downstream actions'
    required: false
    default: ''
outputs:
  version:
    description: 'Version of the log entry found (e.g., 2.0.0)'
  date:
    description: 'Release date of the log entry found (e.g., 2020-08-22)'
  status:
    description: 'Status of the log entry found (prereleased, released, unreleased, or yanked)'
  changes:
    description: 'Description text of the log entry found'
  changes-escaped:
    description: 'Changes text with newlines replaced by the literal string \n and carriage returns stripped, safe for single-line action parameters such as commit_message or tag_message'
  changes-file:
    description: 'Path to the file the changes were written to. Only set when output-file input is provided'
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'file-text'
  color: 'blue'
